In [3]:
import tensorflow as tf
import random

In [18]:
rank_3_tensor = tf.random.uniform([3, 3, 3])

print(rank_3_tensor)

tf.Tensor(
[[[0.63002825 0.52447045 0.31401289]
  [0.2528143  0.6388694  0.2456913 ]
  [0.8516872  0.59571993 0.79640794]]

 [[0.6616638  0.02792096 0.5095129 ]
  [0.1461575  0.4022125  0.9383222 ]
  [0.8066131  0.52155685 0.60326064]]

 [[0.17941141 0.9644885  0.7728027 ]
  [0.91088724 0.7601776  0.21554792]
  [0.47364748 0.7819034  0.46082366]]], shape=(3, 3, 3), dtype=float32)


In [19]:
rank_2_3_tensor = tf.random.uniform([2, 3])

rank_3_4_tensor = tf.random.uniform([3, 4])

print(rank_2_3_tensor)
print(rank_3_4_tensor)

tf.Tensor(
[[0.03810477 0.76950085 0.16883051]
 [0.916693   0.07501626 0.31500137]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0.84674287 0.41832542 0.4363488  0.6359664 ]
 [0.87340975 0.7375437  0.66896796 0.93443656]
 [0.9242976  0.9296428  0.41953015 0.6940738 ]], shape=(3, 4), dtype=float32)


In [20]:
matrix_mult = tf.matmul(rank_2_3_tensor, rank_3_4_tensor)
oper_mult = rank_2_3_tensor @ rank_3_4_tensor

print(matrix_mult)
print(oper_mult)

tf.Tensor(
[[0.8604041  0.7404328  0.6022279  0.8604639 ]
 [1.1328782  0.73164254 0.5823339  0.87171805]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[0.8604041  0.7404328  0.6022279  0.8604639 ]
 [1.1328782  0.73164254 0.5823339  0.87171805]], shape=(2, 4), dtype=float32)


In [21]:
ragged_tensor = tf.ragged.constant([[2, 5, 34], [8, 0]])
print(ragged_tensor)

<tf.RaggedTensor [[2, 5, 34], [8, 0]]>


In [22]:
print(tf.config.experimental.list_physical_devices())

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]


In [23]:
print(ragged_tensor.device.endswith('CPU:0'))

AttributeError: 'RaggedTensor' object has no attribute 'device'